# Generated by Django 4.2 on 2025-01-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('quantity_in_stock', models.FloatField(default=0.0)),
                ('measurement_unit', models.CharField(choices=[('kgs', 'Kilograms'), ('lts', 'Liters')], max_length=10)),
                ('cost_price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'RawMaterial',
                'verbose_name_plural': 'RawMaterials',
            },
        ),
        migrations.CreateModel(
            name='MaterialPurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_logs', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'MaterialPurchaseLog',
                'verbose_name_plural': 'MaterialPurchaseLogs',
            },
        ),
    ]
