# Generated by Django 4.2 on 2025-01-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('measurement_unit', models.CharField(choices=[('kgs', 'Kilograms'), ('lts', 'Liters')], max_length=10)),
                ('cost_price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'RawMaterial',
                'verbose_name_plural': 'RawMaterials',
            },
        ),
    ]
