# Generated by Django 4.2 on 2025-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='measurement_unit',
            field=models.CharField(choices=[('kgs', 'Kilograms'), ('lts', 'Liters'), ('units', 'Units')], max_length=10),
        ),
    ]
