# Generated by Django 4.2 on 2025-01-15 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity_in_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='MaterialPurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_logs', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'MaterialPurchaseLog',
                'verbose_name_plural': 'MaterialPurchaseLogs',
            },
        ),
    ]
