# Generated by Django 4.2 on 2025-01-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_code', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='classifications.producttype')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
            },
        ),
        migrations.CreateModel(
            name='ProductionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='production.production')),
            ],
            options={
                'verbose_name': 'ProductionResource',
                'verbose_name_plural': 'ProductionResources',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_produced', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='production.production')),
            ],
            options={
                'verbose_name': 'ProductionBatch',
                'verbose_name_plural': 'ProductionBatches',
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.FloatField(default=0.0)),
                ('total_volume', models.FloatField(default=0.0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='production.productionbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classifications.product')),
            ],
        ),
    ]
