# Generated by Django 4.2 on 2025-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_code', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
            },
        ),
    ]
