# Generated by Django 4.2 on 2025-01-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_rawmaterial_quantity_in_stock_and_more'),
        ('production', '0002_production_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='production.production')),
            ],
            options={
                'verbose_name': 'ProductionResource',
                'verbose_name_plural': 'ProductionResources',
            },
        ),
    ]
