# Generated by Django 4.2 on 2025-01-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_batchitem_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProductionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('quantity_used', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_resources', to='production.production')),
            ],
            options={
                'verbose_name': 'AdditionalProductionResource',
                'verbose_name_plural': 'AdditionalProductionResources',
            },
        ),
    ]
