# Generated by Django 4.2 on 2025-01-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_additionalproductionresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalproductionresource',
            name='quantity_used',
        ),
    ]
