# Generated by Django 4.2 on 2025-01-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_rename_materials_productionresource_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_produced', models.FloatField(default=0.0)),
                ('ttl_cost', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='production.production')),
            ],
            options={
                'verbose_name': 'ProductionBatch',
                'verbose_name_plural': 'ProductionBatches',
            },
        ),
    ]
