# Generated by Django 4.2 on 2025-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='is_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
