# Generated by Django 4.2 on 2025-01-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productionbatch_is_up_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbatch',
            name='is_up_to_date',
        ),
    ]
