# Generated by Django 4.2 on 2025-01-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
