# Generated by Django 4.2 on 2025-01-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0)),
                ('alias', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Packaging',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raw_materials', models.ManyToManyField(related_name='materials', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'ProductType',
                'verbose_name_plural': 'ProductTypes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=100)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('cost_price', models.FloatField(default=0.0)),
                ('selling_price', models.FloatField(default=0.0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='classifications.packaging')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='classifications.producttype')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
