# Generated by Django 4.2 on 2025-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0)),
                ('alias', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Packaging',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
