# Generated by Django 4.2 on 2025-01-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0002_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='raw_materials',
        ),
    ]
