# Generated by Django 4.2 on 2025-01-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_rawmaterial_quantity_in_stock_and_more'),
        ('classifications', '0003_remove_producttype_raw_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='raw_materials',
            field=models.ManyToManyField(related_name='materials', to='inventory.rawmaterial'),
        ),
    ]
